# .goreleaser.yaml
builds:
  - main: main.go
    id: "cli"
    binary: groups
    goos:
      - linux
      - darwin
      - windows
archives:
  - id: Group-Pairs
    format: binary
    replacements:
      windows: Windows
      darwin: MacOs
      linux: Linux
      386: i386
